### ISSUE TITLE
Project loading doesn't honor bin.laddr

### ISSUE THREAD

**Issue by ElementW** [radareorg/cutter#1347] opened 2019-03-21 00:36 UTC
**Environment information**
* Operating System: Arch Linux x86_64
* Cutter version: `Cutter-v1.8.0-x64.Linux.AppImage`
* File format: raw ARM11 MPCore/ARMv6 code, extracted off the Nintendo 3DS `ns` sysmodule title

**Describe the bug**

Loading a raw binary for the first time in Cutter specifying a load address works, but not when loading from the project save of that same binary.
Loading from the project places the binary at 0x0, rendering the project unusable.
Non-Cutter `r2 -p` loads the project just fine.

**To Reproduce**

1. Get any raw (ARM?) binary
2. Load it from cutter, specifying a `Map offset (-m)` in *Advanced options*
3. Ctrl+S to a project
4. Restart Cutter, load previously saved project

**Expected behavior**

The image is loaded at the specified offset, as is visible in the project's `rc` file.

**Comment by Maijin** [comment] 2019-03-22 21:38
Yep that's a duplicate of https://github.com/radareorg/cutter/issues/1113 but with -m

**Comment by andryblack** [comment] 2019-05-07 11:13
Fixed in radare2 [#11385](https://github.com/radare/radare2/issues/11385)

**Comment by Maijin** [comment] 2019-05-07 11:21
@andryblack thanks for the update, do you know if this is fixing #1113 too, please advise 👍

**Closed by Maijin** 2019-05-07 11:21 UTC
Labels: BUG, radare2
