### ISSUE TITLE
Jump to the Part where a String is beeing called

### ISSUE THREAD

**Issue by gboisec** [radareorg/cutter#857] opened 2018-10-19 18:58 UTC
What feature do I want?

 I'm always frustrated when searching for Strings after finding them I just want to double click on that String and on other dissasemblers like Olly or IDA they jump on the Code where the String is beeing used. This helps a lot to save Time.

Solution?

A Solution would be to double click on the found String and jumping into the function where it is beeing called

**Comment by ITAYC0HEN** [comment] 2018-10-19 20:18
A _string_ can be used several times across a binary, sometimes even hundreds of times -- which usage you want us to "jump" to?

The solution for your issue is to go to the Strings widget, press right-click on the string and choose Xrefs. There you can view previews of all the Xrefs-to the string. If you're using an older version of Cutter - double click on the string and then press 'x'.

![image](https://user-images.githubusercontent.com/20182642/47241688-4867a380-d3f5-11e8-8c9f-5099acb387ca.png)

**Comment by gboisec** [comment] 2018-10-19 20:39
Well as you can see for Congratulations there is no xref, but it should be as you can see in picture two. In Ollydbg I just double click on the string and it jumps in the section as shown in picture two...

![image](https://user-images.githubusercontent.com/42910360/47242595-8c57aa00-d3ef-11e8-9396-25a48290e79c.png)


![image](https://user-images.githubusercontent.com/42910360/47242676-bdd07580-d3ef-11e8-936c-32f492dd6c28.png)

**Comment by Maijin** [comment] 2018-10-20 07:39
Can you provide this binary? This looks like a radare2 analysis problem more than a cutter problem

**Comment by gboisec** [comment] 2018-10-20 08:33
Well this one is from a Course can't share this binary, but I have the same problem with other binaries like the DVIA binary from owasp top 10, here I search for the String "I love Google", but there is no xref ... I will share this binary
[DVIA-v2.zip](https://github.com/radareorg/cutter/files/2497950/DVIA-v2.zip)

**Comment by Maijin** [comment] 2018-10-20 10:34
Definitely not a cutter problem but a radare2 one.

This DVIA binary looks like a very specific analysis case... It is unrelated to the first one because you say you said you are using OllyDBG or that's an iOS binary.

The binary for the course I believe the problem should be fixed in latest r2 from git and will be working in next Cutter if is still reproducible. Can't you share it on telegram or IRC?

For reference to open a r2 issue the xref for this DVIA binary I love google string is

```
Direction	Type	Address	Text
Up	o	__T07DVIA_v240ApplicationPatchingDetailsViewControllerC15showAlertTappedyypF+48	ADRP            X20, #aILoveGoogle@PAGE; "I love Google" (__text:00000001001AC58C)
Up	o	__T07DVIA_v240ApplicationPatchingDetailsViewControllerC15showAlertTappedyypF+4C	ADD             X20, X20, #aILoveGoogle@PAGEOFF; "I love Google" (__text:00000001001AC590)
```

**Comment by Maijin** [comment] 2018-10-20 10:46
Yep the initial one is fixed on radare2 master so it will be working on Cutter next release.

**Comment by Maijin** [comment] 2018-10-20 10:47
I'll close here and we can continue following-up on Radare2 side

**Closed by Maijin** 2018-10-20 10:47 UTC
