### ISSUE TITLE
Mac version crash when trying to opening ESP32 libnet80211.a 

### ISSUE THREAD

**Issue by sst2001** [radareorg/cutter#676] opened 2018-09-05 16:25 UTC
When I select libnet80211.a file, set xentens CPU type, and after few seconds the appliation crash. I changed CPU type with same result. 

When I open an object file .o, it was loaded but failed to disassemble.

**Comment by xarkes** [comment] 2018-09-05 16:57
Hi,
Can you please share the binary? Can you try opening it in radare2 directly, looks more likely a bug in radare2.

**Comment by sst2001** [comment] 2018-09-06 04:40
This is the lib file. 
[libnet80211 2.a.zip](https://github.com/radareorg/cutter/files/2355449/libnet80211.2.a.zip)

**Comment by Maijin** [comment] 2018-09-07 13:26
@sst2001  Provide the information required in the issue template - We are missing tons of information. At this point I can't reproduce in radare2

**Comment by Maijin** [comment] 2018-09-07 13:26
https://github.com/radareorg/cutter/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by xarkes** [comment] 2018-09-30 09:38
Not enough information provided. Closing this.

**Closed by xarkes** 2018-09-30 09:38 UTC
Labels: bug
