### ISSUE TITLE
Navigate to a function by double-clicking it in the graph view

### ISSUE THREAD

**Issue by sdever** [radareorg/cutter#221] opened 2017-12-15 10:04 UTC
When double-clicking on a function in the graph view, nothing happens and I have to switch back to disassembly view in order to navigate to that function which is quite annoying.

**Comment by xarkes** [comment] 2017-12-15 10:14
What version are you using?

**Comment by Maijin** [comment] 2017-12-15 10:34
@sdever ^?

**Comment by sdever** [comment] 2017-12-15 11:20
I guess it was 579ad54757ea6add4488625d17fe1a98c7ef87a5 (trunk of yesterday 19:00), I should retest with the latest trunk this evening.

**Comment by xarkes** [comment] 2017-12-15 11:21
Yes please because I am unable to reproduce.

**Comment by Maijin** [comment] 2017-12-15 11:21
yeah that's fixed now.

**Closed** 2017-12-15 11:30 UTC
