### ISSUE TITLE
ARM/Thumb

### ISSUE THREAD

**Issue by ytrewqytrewqytrewqytrewq1** [radareorg/cutter#270] opened 2018-01-10 09:08 UTC
Cutter does not allow to switch from arm to thumb instructions, it just shows a red line with unaligned.

**Comment by Maijin** [comment] 2018-01-10 09:59
Duplicate of ahb integration here https://github.com/radareorg/cutter/issues/163

**Closed by Maijin** 2018-01-10 09:59 UTC
