### ISSUE TITLE
Better UI for arrows in Disassembly

### ISSUE THREAD

**Issue by Maijin** [radareorg/cutter#1257] opened 2019-03-09 17:27 UTC
**Is your feature request related to a problem? Please describe.**

The arrow in the disassembly are ASCII, they can be improved to be integrated in the UI.

**Describe the solution you'd like**

Switch from arrows from the raw disassembly to Arrows drawed by Cutter

**Comment by XVilka** [comment] 2019-03-09 17:54
Is this a duplicate of https://github.com/radareorg/cutter/issues/933 ?

**Comment by Maijin** [comment] 2019-03-09 17:56
Your issue is going to be splitted

**Comment by XVilka** [comment] 2019-03-09 17:58
Ok, good, just don't forget all items from it, please.

**Comment by xarkes** [comment] 2019-03-13 09:10
So I am marking this as a duplicate of #413.

**Closed by xarkes** 2019-03-13 09:10 UTC
Labels: Enhancement, UI
