### ISSUE TITLE
Right click edit functions

### ISSUE THREAD

**Issue by Maijin** [radareorg/cutter#528] opened 2018-06-09 17:55 UTC
Add right click edit functions in function list and function name in disassembly/graph, it should pop-up a dialog to edit functions:

- Rename
- Change start address
- Change end address
- Change stack frame size `afS`
- Calling convention

Maybe More?

**Comment by sajattack** [comment] 2018-10-01 15:45
Can I take a stab at this one?

**Comment by xarkes** [comment] 2018-10-01 15:50
Yes for sure!
I think this can be done under the already existing "Rename function" option.

**Comment by sajattack** [comment] 2018-10-01 17:30
Another question to clarify, do you want separate menu options or change "Rename function" to "Edit function" and add all the options in one dialog?

**Comment by Maijin** [comment] 2018-10-01 17:33
No, I think we should separate "rename function" because we don't want to bloat the rename dialog with all those stuffs

**Comment by sajattack** [comment] 2018-10-01 20:12
Ok, so rename separate, but the rest together?

**Comment by ITAYC0HEN** [comment] 2018-10-01 20:32
Hi @sajattack, good to have you here - welcome aboard! :)

While right-clicking a function we currently have the option to Rename it ("N" shortcut), this should stay untouched --

![image](https://user-images.githubusercontent.com/20182642/46313938-d9efac80-c5d1-11e8-9568-e99532daa105.png)


The requested addition is a new entry to this context menu, that would open a Dialog with the features mentioned above - this dialog would also have the ability to rename the function. Here's an example --

![image](https://user-images.githubusercontent.com/20182642/46313982-fb509880-c5d1-11e8-9336-6bbf192a6ff6.png)

**Comment by sajattack** [comment] 2018-10-04 03:38
I'm new to Qt. This is what I have for the dialog so far:
![2018-10-03-203628_566x411_scrot](https://user-images.githubusercontent.com/1562711/46451647-35de4080-c74c-11e8-9651-aeaa3cb2f683.png)
How do I do the outlined box to the right?

**Comment by ITAYC0HEN** [comment] 2018-10-04 06:12
hi @sajattack! You did a really good start :)

The screenshot I posted in the issue is just to show the example of the dialog but as I wrote there, we should stick to the original request:

- Rename
- Change start address
- Change end address
- Change stack frame size (afS)

If you think that there are more useful features to add here, that's fine for us. You can see `af?` in radare2 for more options.

**Comment by Maijin** [comment] 2018-10-08 15:16
Someone reported that we should add "edit calling convention" to this list, I have added it. 
The list of calling convention for a given environment is given by `afcl` (`afclj` to be implemented on radare2) and to set it's `afc XXXX`

**Comment by ITAYC0HEN** [comment] 2018-11-23 07:47
fixed in https://github.com/radareorg/cutter/pull/765

**Closed by ITAYC0HEN** 2018-11-23 07:47 UTC
Labels: enhancement, good first issue
