### ISSUE TITLE
Cutter for Mac takes r2 libs from system isntead of frameworks

### ISSUE THREAD

**Issue by trufae** [radareorg/cutter#632] opened 2018-08-18 11:14 UTC
rpath is a bitch
<img width="1164" alt="screen shot 2018-08-18 at 13 02 06" src="https://user-images.githubusercontent.com/6431515/44298736-97effd00-a2e8-11e8-99d3-33ec1f99a59a.png">
<img width="726" alt="screen shot 2018-08-18 at 12 58 13" src="https://user-images.githubusercontent.com/6431515/44298737-9b838400-a2e8-11e8-9729-786277f9b12f.png">

**Comment by thestr4ng3r** [comment] 2018-08-18 11:16
duplicate of #629

**Closed by thestr4ng3r** 2018-08-18 11:16 UTC
