### ISSUE TITLE
Does not run on macOS

### ISSUE THREAD

**Issue by tempodox** [radareorg/cutter#2474] opened 2020-11-14 12:44 UTC
App crashes immediately, with the following diagnosis:

Dyld Error Message:
  Library not loaded: /usr/local/opt/gettext/lib/libintl.8.dylib

There is no `/usr/local/opt` on Darwin.

**Comment by karliss** [comment] 2020-11-14 13:17
Duplicate of  #2428. Please search for existing issues before creating a new one.

**Closed by karliss** 2020-11-14 13:17 UTC
Labels: Duplicate, macOS
