### ISSUE TITLE
macOS could not open file

### ISSUE THREAD

**Issue by roy4801** [radareorg/cutter#981] opened 2018-12-03 13:40 UTC
**Environment information**
* Operating System: OS X El Captian 10.11.6
* Cutter version: Cutter v1.7.2 using r2-3.1.0
* File format: Mach-O executable i386

**Describe the bug**
When using cutter open a Mach-O i386 executable, the app crashes.

**To Reproduce**
1.  Open cutter application, and select new file
2.  Press the open button, and press "ok" without touching any options
3. The screen disappeared, and error log screen poped up

**Expected behavior**
Successfully open the program using Cutter without error report

**Additional context**
```
Dec  3 21:26:11 roy4801s-MacBook-Pro-96 Cutter[3952]: dyld: Symbol not found: _getentropy
	  Referenced from: /Applications/Cutter.app/Contents/MacOS/../Frameworks/Python.framework/Versions/Current/Python (which was built for Mac OS X 10.13)
	  Expected in: /usr/lib/libSystem.B.dylib
```
Full error log: https://gist.github.com/roy4801/c5fd36998ee0b74c13f5a5189a179ffd

**Comment by xarkes** [comment] 2018-12-03 13:50
Might be a duplicate of https://github.com/radareorg/cutter/issues/424.

**Comment by ITAYC0HEN** [comment] 2018-12-03 14:01
if so, our [fix](https://github.com/radareorg/cutter/pull/559) doesn't work?

**Comment by xarkes** [comment] 2018-12-03 14:08
@roy4801 Is it the `.dmg` from the releases tab or did you build it yourself?

**Comment by moreaki** [comment] 2018-12-19 22:16
Same problem here. I suspect since the author's python version is from a OSX 10.13.x machine, there is little that can be done here unless he decides to get OSX 10.11.x inside a VM and run the pyinstaller and all the necessary modules for the build process inside OSX 10.11.x.

**Comment by pelano** [comment] 2018-12-22 13:17
It's not the Python version, it's the SDK: [https://lsongnotes.wordpress.com/2016/09/27/first-blog-post/]

**Comment by Maijin** [comment] 2019-03-22 21:40
Can any of you @moreaki  @roy4801 @pelano  recheck this using the latest available release?

**Comment by moreaki** [comment] 2019-03-23 09:38
@Maijin I have meanwhile upgraded to OSX 10.14.3, after years of resisting. While not exactly thrilled with the reduced battery life, I have now again access to software which was not working anymore previously; Cutter included, which seems to work just fine (except for the missing QTWeb in the build). Long story short: I can't test it anymore if the latest version would actually work on 10.11.x.

**Comment by Maijin** [comment] 2019-03-23 10:55
Ok good so it's really not a cutter issue. Closing here.

**Closed by Maijin** 2019-03-23 10:55 UTC
Labels: BUG, macOS
