### ISSUE TITLE
Changing from CODE -> QWORD in dissembler cause Cutter to crash

### ISSUE THREAD

**Issue by bunjmoha** [radareorg/cutter#842] opened 2018-10-16 21:39 UTC
**Environment information**
* Operating System: Debian 4.18.0--amd64
* Cutter version: 1.7.2 (compiled from src)
* File format: ELF64

**Describe the bug**
Changing from CODE -> QWORD in dissembler cause Cutter to crash

**To Reproduce**
- create a new project
- in Graph is set to (not synced)
- move to Disassembly table
- type an address in the filter textbox 
- change the line at that address from CODE -> QWORD  (OK)
- change the next line following the previous address from CODE -> QWORD 
- Cutter window disappear (crash of Cutter application)

AFTER Deep investigation I found the 0x00002008 has comments that cause the crash

            0x00002004      and  eax, 0x1000a64
            ;-- section..eh_frame_hdr:
            ;-- segment.GNU_EH_FRAME:
            ;-- __GNU_EH_FRAME_HDR:
            0x00002008      add  dword [rbx], ebx ; [17] -r-- section size 60 named .eh_frame_hdr
            0x0000200a      add  edi, dword [rbx]

**Comment by thestr4ng3r** [comment] 2018-10-17 08:03
Can you please share the binary and addresses where exactly you set from code to qword?

**Comment by ITAYC0HEN** [comment] 2018-10-19 20:47
ping @bunjmoha

**Comment by Maijin** [comment] 2018-11-11 09:54
ping2

**Comment by ITAYC0HEN** [comment] 2018-12-15 17:47
Can't reproduce on Windows10 64bit and Arch Linux 64bit. 
Sadly, OP is not answering - closing. Will re-open upon request

**Closed by ITAYC0HEN** 2018-12-15 17:47 UTC
Labels: bug
