### ISSUE TITLE
Crash when loading dbgeng.pdb

### ISSUE THREAD

**Issue by poizan42** [radareorg/cutter#1249] opened 2019-03-07 12:18 UTC
**Environment information**
* Operating System: Windows 10.0.18348.1
* Cutter version: 1.7.4
* File format: (pdb?)

**Describe the bug**
Cutter crashes when importing the pdb for dbgeng.dll version 10.0.16299.15 (timestamp 0xBCB20840)

**To Reproduce**
1. Download https://msdl.microsoft.com/download/symbols/dbgeng.pdb/BBC025D742C1212027B8441100104CFD1/dbgeng.pdb
2. Open any file in Cutter
3. Go to File->Import PDB
4. Choose the file downloaded in step 1
5. Cutter crashes with STATUS_HEAP_CORRUPTION (0xC0000374)

**Expected behavior**
The pdb file is imported without Cutter crashing...

**Comment by Maijin** [comment] 2019-03-07 15:24
Hello @poizan42,

I cannot reproduce in current radare2 master, so likely this issue has already been fixed and the next release will be fixing this issue.

**Comment by Maijin** [comment] 2019-03-21 18:10
This should be fixed now, please download Cutter 1.8.0 and confirm. Reopen if necessary.

**Closed by Maijin** 2019-03-21 18:10 UTC
Labels: BUG, radare2
