### ISSUE TITLE
Right click to show the disassembly context menu

### ISSUE THREAD

**Issue by Maijin** [radareorg/cutter#1959] opened 2019-12-21 10:29 UTC
**Environment information**
* Operating System: Win10 [Version 10.0.18362.535] and Mac OS
* Cutter version: 1.10
* File format: Any

**Describe the bug**

When right clicking in the graph the disassembly context menu is not shown, only the graph options.

**To Reproduce**

1. Go to graph mode
2. Right click on an opcode/instructions

**Screenshots**
<img width="943" alt="image" src="https://user-images.githubusercontent.com/1408600/71306781-2563c580-23e5-11ea-9d3f-ed6f892b9134.png">

**Comment by karliss** [comment] 2019-12-21 10:58
Likely a duplicate of #1825. I started working on this in https://github.com/karliss/cutter/tree/graph-dpi but got stuck due to not having windows dev setup prepared. I recently did it so work can be resumed.

**Closed** 2019-12-22 18:56 UTC
Labels: BUG, High Priority
