### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by junknet** [radareorg/cutter#2326] opened 2020-07-23 20:11 UTC
cutter version:git latest             (commit:7ca6a1eda0e4eef2371d05a4fc099b0985043772
  cd cutter；
  `git submodule update --init --recursive`
  so radare2 version: 4.5.0         (commit:9d7eda5ec7367d1682e489e92d1be8e37e459296
r2ghidra-dec version: git latest (commit:17ec3b3041e21f0492878e1d3147cdcd5830ae00

cutter build command:
`cmake -DCMAKE_INSTALL_PREFIX=/usr -DCUTTER_USE_BUNDLED_RADARE2=ON -DCUTTER_ENABLE_PYTHON=true -DCUTTER_ENABLE_PYTHON_BINDINGS=true   ../src -G Ninja`  and install

r2ghidra-dec build command:
`cmake -DCMAKE_INSTALL_PREFIX=/usr -DBUILD_CUTTER_PLUGIN=ON -DCUTTER_SOURCE_DIR=/home/ruben/Desktop/cutter -G Ninja ..`  and install

everthing is ok，but if i select Windows->Decompile，crash!
And then nothing left,Windows suddenly disappear from the desktop.

I tried to start it with GDB，and then select Windows->Decompile
This is GDB's information
![qwe](https://user-images.githubusercontent.com/55597646/88361830-f7949400-cdac-11ea-95aa-cd34ea2a7385.png)

**Comment by ITAYC0HEN** [comment] 2020-07-23 20:30
Hi, thank you for opening an issue :)
Seems like you didn't fill the issue template and thus, your issue is lacking important information we need to know.

Specifically, what is the version of radare2 you have installed? Did you make sure all three. repositories are up to date? What is the output you receive? When you execute Cutter without plugins "--no-plugins" the crash still happen? 

Please fill the issue with all the detailed and relevant information so we will be able to fully help you.
Attach files, screenshots and reproducers if you can.

Thanks!

**Comment by junknet** [comment] 2020-07-24 04:56
cutter version:git latest             (commit:7ca6a1eda0e4eef2371d05a4fc099b0985043772
  cd cutter；
  `git submodule update --init --recursive`
  so radare2 version: 4.5.0         (commit:9d7eda5ec7367d1682e489e92d1be8e37e459296
r2ghidra-dec version: git latest (commit:17ec3b3041e21f0492878e1d3147cdcd5830ae00

cutter build command:
`cmake -DCMAKE_INSTALL_PREFIX=/usr -DCUTTER_USE_BUNDLED_RADARE2=ON -DCUTTER_ENABLE_PYTHON=true -DCUTTER_ENABLE_PYTHON_BINDINGS=true   ../src -G Ninja`  and install

r2ghidra-dec build command:
`cmake -DCMAKE_INSTALL_PREFIX=/usr -DBUILD_CUTTER_PLUGIN=ON -DCUTTER_SOURCE_DIR=/home/ruben/Desktop/cutter -G Ninja ..`  and install

everthing is ok，but if i select Windows->Decompile，crash!
And then nothing left,Windows suddenly disappear from the desktop.

I tried to start it with GDB，and then select Windows->Decompile
This is GDB's information
![qwe](https://user-images.githubusercontent.com/55597646/88361830-f7949400-cdac-11ea-95aa-cd34ea2a7385.png)

**Comment by karliss** [comment] 2020-07-24 05:23
Looks like you might be mixing multiple R2 versions. You compiled Cutter with CUTTER_USE_BUNDLED_RADARE2=ON. But r2ghidra during compilation most likely used system r2.

I don't recommend using CUTTER_USE_BUNDLED_RADARE2=ON for system installation. This option is more aimed at development builds.

**Comment by junknet** [comment] 2020-07-24 09:44
I install a new OS the same as mine on the other computer.
So I can guarantee that I only have one version of R2.
Repeat all the steps above.

Crash!

**Comment by junknet** [comment] 2020-07-24 09:45
> Looks like you might be mixing multiple R2 versions. You compiled Cutter with CUTTER_USE_BUNDLED_RADARE2=ON. But r2ghidra during compilation most likely used system r2.
> 
> I don't recommend using CUTTER_USE_BUNDLED_RADARE2=ON for system installation. This option is more aimed at development builds.

I install a new OS the same as mine on the other computer.
So I can guarantee that I only have one version of R2.
Repeat all the steps above.

Crash!

**Comment by karliss** [comment] 2020-07-24 09:51
Please do the following steps:
* clean up all the old installations
* Build and install r2 using r2 source that matches with submodule
* Build cutter with `CUTTER_USE_BUNDLED_RADARE2=OFF`
* Build r2ghidra

**Comment by junknet** [comment] 2020-07-24 10:17
> Please do the following steps and confirm if it still crashes:
> 
>     * clean up all the old installations
> 
>     * Build and install r2 using r2 source that matches with submodule
> 
>     * Build cutter with `CUTTER_USE_BUNDLED_RADARE2=OFF`
> 
>     * Build r2ghidra

I did as you said.  Crash!

cutter : git latest   
build command:`cmake -DCMAKE_INSTALL_PREFIX=/usr -DCUTTER_USE_BUNDLED_RADARE2=OFF -DCUTTER_ENABLE_PYTHON=true -DCUTTER_ENABLE_PYTHON_BINDINGS=true ../src -G Ninja`

radare2: _commit 9d7eda5ec7367d1682e489e92d1be8e37e459296 (HEAD -> master, tag: 4.5.0)_
build&install : `sys/install.sh`

r2ghidra: git latest
build command: `cmake -DCMAKE_INSTALL_PREFIX=/usr -DBUILD_CUTTER_PLUGIN=ON -DCUTTER_SOURCE_DIR=/home/ruben/Desktop/cutter -G Ninja ..`

**Comment by karliss** [comment] 2020-07-24 10:51
I still haven't seen you answer of what happens when you run cutter with "--no-plugins" flag.

Does it actually crashes or does the UI freezes and you kill it either directly or with a popups that shown shows? 

What happens if you try running decompiler in the console widget using `pdg` command?

The output you posted earlier from gdb doesn't look like crash more like something calling exit. You can try setting a breakpoint in exit method by calling `break exit` in gdb before starting the executable.

Does resetting Cutter settings have any effect? Have you tried more than one executable? Does it happens with any function in the executable?

**Comment by junknet** [comment] 2020-07-24 13:29
> I still haven't seen you answer of what happens when you run cutter with "--no-plugins" flag.
> 
> Does it actually crashes or does the UI freezes and you kill it either directly or with a popups that shown shows?
> 
> What happens if you try running decompiler in the console widget using `pdg` command?
> 
> The output you posted earlier from gdb doesn't look like crash more like something calling exit. You can try setting a breakpoint in exit method by calling `break exit` in gdb before starting the executable.
> 
> Does resetting Cutter settings have any effect? Have you tried more than one executable? Does it happens with any function in the executable?


run cutter with "--no-plugins" everthing  works fine.

I just select Decompile window, it crash. (The entire window disappears,and cutter is not in the process tree.)

resetting Cutter settings have no effect, i only start one executable, other functions are normal,except show decompile window.

`pdg` command work fine.



I rebuild with debug symbol and use gdb set breakpoint `catch syscall exit exit_group` ,by the way `break exit` not working

This is crash 
![qwe](https://user-images.githubusercontent.com/55597646/88395759-24b86500-cdf4-11ea-8d67-6eefdb1a2334.png)

![bt](https://user-images.githubusercontent.com/55597646/88396213-cb9d0100-cdf4-11ea-80e1-c20b3d64a4cf.png)



`

**Comment by karliss** [comment] 2020-08-24 11:09
As can be seen in the stacktrace exit is called from dynamic loader methods. Most likely when the cutter half of r2ghidra plugin tries to access methods from r2 plugin it can't find them doesn't find them. M

**Comment by ITAYC0HEN** [comment] 2020-08-31 12:38
Thank you for opening this issue. It seems like the version mismatch was responsible for the problem. As the issue is resolved, I will close it, 

If it wasn't, please feel free to re-open this issue and we would love to help :)

**Closed by ITAYC0HEN** 2020-08-31 12:38 UTC
