### ISSUE TITLE
Add/fix the ability to rename local variables and arguments

### ISSUE THREAD

**Issue by ITAYC0HEN** [radareorg/cutter#531] opened 2018-06-10 07:47 UTC
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Arch Linux x64
| File format of the file you reverse (mandatory)      | PE
| Architecture/bits of the file (mandatory)            | 64
| Cutter and r2 version, See About Cutter (mandatory)  | Version 1.4 / Using r2 2.6.0-117-g27816462c

### Expected behavior
Right-click on a local variable /argument to rename it. For example, from `[local_30h]` to `coolName`.

### Actual behavior
Cutter is failed to recognize the flag to be changed (both in graph and disas widgets) 
![image](https://user-images.githubusercontent.com/20182642/41199456-2a7b6ab2-6c9b-11e8-968f-d1383543766b.png)

As for now, I used `afvn oldanme newname` from the console.

### Steps to reproduce the behavior 
Go to a function, right click on a local argument/variable and try to rename it.

**Comment by ITAYC0HEN** [comment] 2018-06-22 12:07
I believe that the problem is from radare at [`cmd_an()` ](https://github.com/radare/radare2/blob/122cb395e988dad114b54b1483fd6210d719b012/libr/core/cmd_anal.c#L800)

```
[0x0040139b]> an
0xfffffffffffffff4

[0x0040139b]> anj
[{"type":"address","offset":-12}]
```

**Comment by xarkes** [comment] 2018-07-01 08:29
Looks fixed on master.

**Comment by ITAYC0HEN** [comment] 2018-07-01 08:32
Is there any PR as a reference?

**Comment by xarkes** [comment] 2018-07-01 08:32
Nope, maybe in radare2, but at least I cannot reproduce.

**Comment by ITAYC0HEN** [comment] 2018-07-01 08:35
Oh yeah, I remember I checked and saw that the problem is in r2. Sadly I'll
be afk for a while so can't really check.

If you say so, I believe you

**Comment by xarkes** [comment] 2018-07-01 08:35
Ideally I should check on the same binary as you, but I tried with different ones and it looks good.
Worst case, you can still reopen the issue.

**Closed by xarkes** 2018-07-01 08:35 UTC
Labels: bug

**Comment by ITAYC0HEN** [comment] 2018-07-01 08:37
iirc it's Dropshot. You can find the binary in the articles I published on
Cutter. The addresses are in the screenshot.

**Comment by xarkes** [comment] 2018-07-01 08:41
Confirmed, fixed.
