### ISSUE TITLE
Dark Mode graph bbs are white

### ISSUE THREAD

**Issue by GustavoLCR** [radareorg/cutter#1507] opened 2019-05-07 16:49 UTC
**Environment information**
* Operating System: Windows 10
* Cutter version: 1.8.1 (Latest Appveyor build)
* File format: pe64
 * Arch: x86
 * Type: EXEC (Executable file)

**Describe the bug**
Non-selected basic blocks in the graph are white so the text is hard to see.

**To Reproduce**
1. Enable dark mode
2. Open a file
3. Analize functions
3. Switch to graph tab

**Expected behavior**
The non-selected blocks are some other variation of dark-grey

**Screenshots**
![myeyeshurt](https://user-images.githubusercontent.com/23562137/57317430-73ce8900-70ce-11e9-9ed1-964c881e24e1.png)

**Comment by karliss** [comment] 2019-05-07 17:06
What color theme are you using? I didn't notice anything similar while working on overview colors not being updated.

**Comment by GustavoLCR** [comment] 2019-05-07 19:33
Im using ayu. but it doesn't seems to matter

Em ter, 7 de mai de 2019 às 14:06, karliss <notifications@github.com>
escreveu:

**Comment by karliss** [comment] 2019-05-23 15:24
@GustavoLCR did you meant cutter dark theme or native theme+windows 10 dark mode?

**Comment by optizone** [comment] 2019-05-23 15:30
@GustavoLCR you can copy this theme and edit background color of graph node

**Comment by ITAYC0HEN** [comment] 2019-05-23 15:38
> @GustavoLCR you can copy this theme and edit background color of graph node

It is not really a solution

**Comment by ITAYC0HEN** [comment] 2019-05-23 15:42
I can't reproduce the bug and from the image, it seems like Cutter's dark theme.
@GustavoLCR Can you try to reset your settings? 
Click on View -> Reset Settings and then close and re-open cutter. Then please let us know if you still experience the issue.

Also, you can also try to remove entirely the configuration file. Most likely in `C:\Users\user\AppData\Roaming\RadareOrg\Cutter.ini`
remove the old one (most likely in

**Comment by GustavoLCR** [comment] 2019-05-23 15:43
It is cutter's dark mode. And yes, if I manually edit the theme I can make
the blocks dark but that should be the default if dark mode is on

Em qui, 23 de mai de 2019 12:38, Itay Cohen <notifications@github.com>
escreveu:

**Comment by GustavoLCR** [comment] 2019-05-23 15:44
Ill try it once i get to my pc

Em qui, 23 de mai de 2019 12:42, Itay Cohen <notifications@github.com>
escreveu:

**Comment by ITAYC0HEN** [comment] 2019-05-23 15:49
you are completely right. This should be the default and there is misbehavior. I can't reproduce it so we will wait for your testing.
And please make sure to update to the new release :)
Thanks!

**Comment by optizone** [comment] 2019-05-23 18:43
Actually, it seems odd that you have pure black background, because for all radare2 standard color themes Cutter uses this color as background (he code #25282B)
![image](https://user-images.githubusercontent.com/42874998/58277908-79e98880-7da3-11e9-9341-01b1baae7265.png)

**Comment by GustavoLCR** [comment] 2019-05-23 18:49
Found the problem:

 I had a `~/.local/share/radare2` folder from a radare2 installation that was messing up with the loaded themes, I guess cutter got confused and treats themes differently depending where it's loaded from?, so when I deleted it cutter was fixed.

I also noticed that cutter saves modified themes on that folder so that probably was it.

**Comment by ITAYC0HEN** [comment] 2019-05-23 19:53
Very nice, good catch and thank your for reporting! :) 
I will close the issue for now. But maybe @optizone can suggest a solution to avoid such confusions next time

**Closed by ITAYC0HEN** 2019-05-23 19:53 UTC
Labels: BUG
