### ISSUE TITLE
Cutter 1.4 crashes on Linux (stack smashing detected)

### ISSUE THREAD

**Issue by davidbrazdil** [radareorg/cutter#522] opened 2018-06-07 10:58 UTC
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Debian sid x86/64
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | x86/64
| Cutter and r2 version, See About Cutter (mandatory)  | Version 1.4 / Using r2 2.5.0-105-gc79874941

### Expected behavior
See IDE

### Actual behavior
Get "stack smashing detected" error in the terminal

```
*** stack smashing detected ***: ./Cutter-v1.4-x86_64.AppImage terminated
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x70bcb)[0x7fcad0600bcb]
/lib/x86_64-linux-gnu/libc.so.6(__fortify_fail+0x37)[0x7fcad06891b7]
/lib/x86_64-linux-gnu/libc.so.6(__fortify_fail+0x0)[0x7fcad0689180]
/usr/lib/x86_64-linux-gnu/libcrypto.so.1.1(+0x1a95d1)[0x7fca625645d1]
```
### Steps to reproduce
Run Cutter AppImage, select file (attached), click Open, leave default config, click OK, observe crash.

### Additional Logs, screenshots, source-code,  configuration dump, ...
Tested binary is in the attached 'veridex-linux.zip', file called 'veridex'.
Also attached the full log.txt.

[veridex-linux.zip](https://github.com/radareorg/cutter/files/2080086/veridex-linux.zip)
[log.txt](https://github.com/radareorg/cutter/files/2080099/log.txt)

**Comment by xarkes** [comment] 2018-06-09 08:12
Well it's hard to tell what is wrong here.
I tried with the latest AppImage and I cannot reproduce this crash...

**Comment by xarkes** [comment] 2018-06-26 09:49
Can anyone reproduce this?

**Comment by fcasal** [comment] 2018-06-26 10:06
Takes some time but opens fine for me on both the latest Appimage and master.

**Comment by xarkes** [comment] 2018-06-26 10:50
Ok thanks, I'm closing, feel free to reopen if it still happens with the upcoming 1.5 release.

**Closed by xarkes** 2018-06-26 10:50 UTC
Labels: bug
