### ISSUE TITLE
Marking text with mouse in disassembly not possible past screen

### ISSUE THREAD

**Issue by FalcoGer** [radareorg/cutter#2169] opened 2020-04-25 17:07 UTC
**Environment information**
* Operating System:
> Ubuntu Mate 18.04
Linux **** 4.15.0-96-generic #97-Ubuntu SMP Wed Apr 1 03:25:46 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

* Cutter version:
> Version 1.10.3
Using r2-4.4.0
Based on Qt 5.14.2 (GCC 9.3.0, 64 bit)
Optional Features:
Python: ON
Python Bindings: ON

* Obtained from:
  - [x] Built from source
  - [ ] Downloaded from release
  - [ ] Distribution repository

* File format: Any

**Describe the bug**

Marking text with mouse is not behaving intuitively

* When clicking and dragging with the mouse in the disassemble window and moving the mouse to the top or bottom of the screen, then the text doesn't scroll as it would in a normal editor
* When left clicking at some point to place the cursor there and then scrolling the text off screen, and then shift + left clicking to mark the whole section, really only the text on screen is marked. Copying with ctrl + c only copies whatever is currently in view, not the whole segment.

This is a problem when you want to copy the code because then you have to copy multiple times, which is quite annoying.

**To Reproduce**

1. Open a file for disassembly
2. Open disassembly window
3. Click on some character and hold down the left mouse button
4. Hold the mouse button and drag it to the bottom edge of the screen to select multiple lines
5. Observe that you can't mark more than one page of text, less if you started step 3 in the middle and not at the top.

**Expected behavior**

The view will scroll the text, marking continues and the text that has been scrolled off screen will be kept marked.

**Screenshots**

**Additional context**

QT built from source (tag 5.14.2).
PySide built from source (master).
Cutter built from source (master @ aa8ecee)

**Comment by karliss** [comment] 2020-04-25 17:26
Duplicate of #1830

**Closed** 2020-05-01 18:40 UTC
