### ISSUE TITLE
Add right click add a flag in Hex Panel

### ISSUE THREAD

**Issue by Maijin** [radareorg/cutter#1520] opened 2019-05-12 09:45 UTC
**Is your feature request related to a problem? Please describe.**

To be able to quickly add flag when noticing a pattern.

**Describe the solution you'd like**

Reuse the code from disassembly/graph to add right click add a flag in Hex Widget

**Comment by karliss** [comment] 2019-05-12 17:58
Duplicate of #1069

**Closed** 2019-05-12 19:18 UTC
Labels: Enhancement, good first issue
