### ISSUE TITLE
Mouse cursor highlight comment only instead of full command

### ISSUE THREAD

**Issue by dmknght** [radareorg/cutter#784] opened 2018-10-09 08:14 UTC
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Debian testing amd64
| Cutter and r2 version, See About Cutter (mandatory)  | Version 1.7.2 / Using r2 3.0.0 |

# Suggestion
Every time I move mouse cursor on a command in graph mode, it shows me that command in highlight box. I think it is not necessary and showing comments only is more useful. I also think a `hide comments` option is good and it gonna save many space in graph.

**Comment by ITAYC0HEN** [comment] 2018-10-12 07:36
can you share a screenshot which demonstrate the problem?

**Comment by dmknght** [comment] 2018-10-12 07:54
Here is my screenshot. I am very sorry for bad image quality. My Cinnamon can't take screenshot with comment box under mouse so I have to do it in the hard way.
![img_20181012_144159](https://user-images.githubusercontent.com/29118926/46855467-fee3eb00-ce2d-11e8-927d-a616a5758ebd.jpg)
Anyway, i think i had some mistakes:
1. This box only shows up when mouse move to comment (not instruction)
2. Looks like it works when asm.slow is enabling
My suggestions:
1. Show comment only in that box every time mouse move to command (in this picture, this box show instruction, register,...)
2. Add option that graph panel show comments using mouse cursor only.

**Comment by dmknght** [comment] 2018-10-12 09:04
Here is my better screenshot.
![screenshot from 2018-10-12 16-03-05](https://user-images.githubusercontent.com/29118926/46859614-728af580-ce38-11e8-9a6e-840ea6f07ecb.png)

**Comment by ITAYC0HEN** [comment] 2019-02-12 14:52
is this still occur?

**Comment by dmknght** [comment] 2019-02-13 08:32
Yes it is still the same.

**Comment by ITAYC0HEN** [comment] 2019-02-17 08:05
@dmknght want to try and fix it?

**Comment by dmknght** [comment] 2019-02-17 17:34
I'm not sure. I don't know much about Cpp programming. I am having some idea about this but unfortunately I can't figure it out in the source code :(

**Comment by ITAYC0HEN** [comment] 2019-03-12 21:11
I can't reproduce the tooltips in GRaph mode at all

**Comment by xarkes** [comment] 2019-03-13 08:59
I can't reproduce. Closing.

**Closed by xarkes** 2019-03-13 08:59 UTC
Labels: Enhancement, Question, UI
