### ISSUE TITLE
Bug in graph overview when changing theme

### ISSUE THREAD

**Issue by JorgeTebruski** [radareorg/cutter#1496] opened 2019-04-30 01:06 UTC
**Environment information**
* Operating System: windows 10
* Cutter version: 1.8.1
* File format: 
 * Arch: 
 * Type: 

**Describe the bug**

When switching from light theme to dark theme, the background of the graph overview still remains white.

**To Reproduce**

1. Change QT theme to light
2. Change QT theme to dark

**Expected behavior**

When switching from light theme to dark theme, the background of the graph overview becomes dark.

**Screenshots**

![Anotação 2019-04-29 214954](https://user-images.githubusercontent.com/38569298/56935697-30ba5780-6ac9-11e9-8efd-d0a9fe29f345.jpg)

**Additional context**

The graph overview background returns to normal when you open another function.

**Comment by ITAYC0HEN** [comment] 2019-05-03 08:45
I couldn't reproduce
![graph_light_to_dark](https://user-images.githubusercontent.com/20182642/57127371-d9520b00-6d98-11e9-8bf7-e926ea55fe14.gif)

**Comment by xarkes** [comment] 2019-05-03 10:53
In the original issue, the problem appears on Windows, and I think you are under linux in the gif, am I right?

**Comment by JorgeTebruski** [comment] 2019-05-03 13:38
![BugTheme](https://user-images.githubusercontent.com/38569298/57140772-f41f8200-6d8e-11e9-925a-f8c49c236ce1.gif)

When trying again, the bug occurred only in the native theme. This seems to be random.

**Comment by ITAYC0HEN** [comment] 2019-05-04 06:46
@optizone maybe you can figure out the reason?

**Comment by karliss** [comment] 2019-05-04 09:31
I was able to repeat a similar problem on Linux by changing only color them not interface theme.
* copy a light color theme
* switch to dark interface theme
* switch between one of dark color themes and copied light color theme, observe that overview doesn't get updated.

I guess that @JorgeTebruski being able to repeat it only with native theme is related to fact that native interface theme allows selecting any color theme but dark/light only matching dark/light half of color themes.
Custom/copied color themes are available for both light and dark interface themes which is how I was able to observe it. Looks like it also happens when switching between two builtin light color themes but is more difficult to spot as difference in edge color is less obvious.

**Comment by optizone** [comment] 2019-05-04 09:41
Actually, it is old bug. Background of overview does not changes after `Configuration::colorsUpdated` immediately, but if you drag and drop this widget, it updates. Seems like cache issue.

**Comment by karliss** [comment] 2019-05-04 10:00
Adding setCachDirty to OverviewView::refreshView helped.

**Comment by optizone** [comment] 2019-05-04 10:27
@ITAYC0HEN is it just me or when light theme is selected text in interface theme combo box is the same color as background?

https://github.com/radareorg/cutter/issues/1496#issuecomment-489013136

**Comment by optizone** [comment] 2019-05-04 18:38
@karliss will you send PR so we can close the issue?

**Closed** 2019-05-06 08:30 UTC
Labels: BUG
