### ISSUE TITLE
Register or name in graph view is not always selected when clicking

### ISSUE THREAD

**Issue by Kezii** [radareorg/cutter#1255] opened 2019-03-09 13:47 UTC
**Environment information**
* Operating System: Arch Linux
* Cutter version: 1.7.4.r108.g687ef2d7-1
* File format:

**Describe the bug**
Since the latest update, when clicking a register/word in graph view, the register is not always selected

**To Reproduce**
Open graph view, click random registers a dozen times and notice that sometimes the register is not selected, and you have to click another register to finally select it

**Expected behavior**
The register should be selected the first time it is clicked

**Additional context**
I'm pretty sure that it's a recent regression, i have not noticed this before

**Comment by ITAYC0HEN** [comment] 2019-03-10 09:21
Reproducer:
![2019-03-10_11-20-23](https://user-images.githubusercontent.com/20182642/54082991-8fafeb80-4326-11e9-986d-df933f335dd6.gif)

whenever my cursor is on a register I click it, which obviously hard to see in gif.

**Comment by a1ext** [comment] 2019-03-10 10:27
I think the problem is that there is a check of current ea has changed, if so it will redraw and update highlight token

**Comment by ITAYC0HEN** [comment] 2019-07-13 16:06
I think this is now fixed since I can't reproduce anymore.
@Kezii @a1ext if you experience it again please comment here or open the issue :)
thanks!

**Closed by ITAYC0HEN** 2019-07-13 16:06 UTC
Labels: BUG, UI
