### ISSUE TITLE
Cutter 1.4 crashes on windows 10 when opening project

### ISSUE THREAD

**Issue by wavvs** [radareorg/cutter#501] opened 2018-05-21 21:26 UTC
| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Windows  10 x64
| File format of the file you reverse (mandatory)      | PE32
| Architecture/bits of the file (mandatory)            |  x86
| Cutter and r2 version, See About Cutter (mandatory)  | Version 1.4 / r2-2.5.0-105-gc79874941

Steps to reproduce:
1. Open the binary (https://malshare.com/sample.php?action=detail&hash=49dbf3e4a78e87f87f0bfd90d9e42338)
2. Analysis - Level: Advanced, check all checkboxes (maybe it's variative, I disabled renaming based on context)
3. Save to the project (default checkboxes, didn't test with others), close Cutter.
4. Try open the project -> Crash

Edit: This is related issue, xrefs don't work if some of checkboxes selected (don't know which exactly)

**Comment by xarkes** [comment] 2018-06-09 10:15
Hello, can you share directly the binary here? (drag and drop it) I cannot download the sample.

**Comment by Maijin** [comment] 2018-06-09 10:22
And follow the template to create issue as we don't know which version you are using.

**Comment by wavvs** [comment] 2018-06-09 10:43
@xarkes 
[49dbf3e4a78e87f87f0bfd90d9e42338.zip](https://github.com/radareorg/cutter/files/2086881/49dbf3e4a78e87f87f0bfd90d9e42338.zip)
@Maijin it's in the title, cutter 1.4 release version

**Comment by Maijin** [comment] 2018-06-09 10:55
That's not what the template is requesting, 1.4 can be git, can be non-git, can be OSX, can be linux, can be windows, can be something else, please use the template we can't guess.

**Comment by Maijin** [comment] 2018-06-09 10:55
same for the radare2 version

**Comment by wavvs** [comment] 2018-06-09 11:15
Why do I need explicitly paste r2 version if you ship it along with cutter? Ughh...

**Comment by xarkes** [comment] 2018-06-09 11:18
I think Maijin meant you didn't specifiy if you compiled it yourself, or if you were using the latest release.
Hence those information.

**Comment by Maijin** [comment] 2018-06-09 11:27
Thanks for using the template ;)

**Comment by xarkes** [comment] 2018-06-21 09:17
Just noticed that was because of projects.
Projects on radare2 side are very shitty (produces many wrong files) and I think that's mostly why Cutter crashes here.

**Comment by xarkes** [comment] 2018-07-01 12:15
So yeah I think projects are too broken to be actually used in Cutter.
We really need to refactor the projects in radare2.

**Comment by wavvs** [comment] 2018-07-01 21:16
Need to open issue on radare2 side?

**Comment by xarkes** [comment] 2018-07-01 21:40
Not really, the problem is mainly that projects are not stable at all. For that radare2 needs some big refactoring (and it's already tracked in issues I think).
While I know it is an important feature, all I can suggest is to not use projects for now...

**Comment by Maijin** [comment] 2018-07-02 04:23
CC @radare maybe need prioritization for one of the future release 🤔

**Comment by boondoggler** [comment] 2018-08-29 17:44
Just to add: I am seeing this on Cutter 1.7.1 on both Linux Debian 9 and Windows 10 x64.

On mine it doesn't crash it just eats up 100% CPU forever

Brilliant project, but this makes it unusable as all work in unsavable

**Comment by xarkes** [comment] 2018-08-29 23:07
Yep, this is something we want to improve, but it requires quite a lot of changes in radare2 codebase.

**Comment by ITAYC0HEN** [comment] 2018-11-03 10:51
Did not crash anymore on windows10 64bit nor on Debian or Arch (64 bit both).
I think this is fixed now after some improvements we did for Cutter and Radare2 projects.
I'm closing this issue for now, @wavvs, please inform us if the problem still occurs on the latest version (from Master).

Thank you! :)


p.s. - @boondoggler, please check if your issue is happening as well (latest Cutter from master) and if so, we should open an issue for this.

**Closed by ITAYC0HEN** 2018-11-03 10:51 UTC
Labels: bug, radare2
