### ISSUE TITLE
Immediate base change memory reference not opcode operand 2

### ISSUE THREAD

**Issue by Th4nat0s** [radareorg/cutter#1962] opened 2019-12-21 15:55 UTC
**Environment information**
* Operating System: Win 10
* Cutter version: 1.10.0
* File format: PE dll

**To Reproduce**

When i set a immediate base it is applied strangely ..

On this one, it is getting well
![image](https://user-images.githubusercontent.com/1728186/71310237-03cd0300-2412-11ea-9404-c079ce1a49b9.png)
When re setting the decoding to ASCII it change it to 
![image](https://user-images.githubusercontent.com/1728186/71310244-147d7900-2412-11ea-8343-a3cea22fe85a.png)
No issues.

But in this case; 
![image](https://user-images.githubusercontent.com/1728186/71310252-3aa31900-2412-11ea-82d0-a0f399a2e6e1.png)
When I try to display 0x78 in Ascii , it change the reference of memory offset.  Note that i had selected the 0x78 then right click
![image](https://user-images.githubusercontent.com/1728186/71310261-55758d80-2412-11ea-81b7-0b47167762fd.png)
It's only visible when you set an "visible" format like IP 
![image](https://user-images.githubusercontent.com/1728186/71310271-6aeab780-2412-11ea-9f21-43403843873d.png)

**Expected behavior**
Changing the 0x78 to ascii

**Additional context**
This remove the "change" issue not working of https://github.com/radareorg/cutter/issues/1960

It is a R2 issue isn't it ?

**Comment by karliss** [comment] 2019-12-21 16:38
Currently Cutter applies the immediate base change to first immediate value regardless of what is clicked. As can be seen in your example there can be more than one immediate value in single instruction.  

Currently Cutter has very poor understanding of mapping between string tokens in disassembly and what they represent. 
 Having such mapping would be very helpful for many features that involve clicking on an item in disassembly, but implementing it will take significant effort.

**Comment by karliss** [comment] 2019-12-21 16:41
Related #1033

**Comment by karliss** [comment] 2019-12-21 22:45
Closing this as duplicate of #1033.

**Closed by karliss** 2019-12-21 22:45 UTC
Labels: Duplicate

**Comment by Maijin** [comment] 2019-12-24 11:42
Duplicate of #
