### ISSUE TITLE
Bug in the metadata tab [UI Bug]

### ISSUE THREAD

**Issue by 0x913** [radareorg/cutter#2058] opened 2020-02-12 14:33 UTC
**Environment information**
* Operating System: Windows 10
* Cutter version: 1.10.1 x64
* Obtained from:
  - [] Built from source
  - [x] Downloaded from release
  - [ ] Distribution repository
* File format:
-
**Describe the bug**

So i was messing around with cutter and under preferences -> dissasembly -> metadata it came to my attention that when you would klick enable on "show only strings if any in the asm.emu output (emu.str)" and disable it that "Run ESIL emulation analysis" would be turned on without me enabling it to disable it you would need to enable and disable it by klicking the checkbox and then it would be fixed.

**To Reproduce**

1. Open Preferences -> Dissasembly -> Metadata tab

2. Click on -> "Show only strings if any in the asm.emu output (emu.str)"
                        whilst "Run ESIL emulation analysis  (asm.emu)" is not enabled.

3. Disable "Show only strings if any in the asm.emu output (emu.str)" and
    you will se that "Run ESIL emulation analysis  (asm.emu)" is  enabled.

4. Enable and Disable "Run ESIL emulation analysis  (asm.emu)" to fix the  Problem

**Expected behavior**
enable and disable "Show only strings if any in the asm.emu output (emu.str)" and
    you will se that "Run ESIL emulation analysis  (asm.emu)" is  enabled.

**Screenshots**

**Additional context**

**Comment by ITAYC0HEN** [comment] 2020-02-12 14:57
Thank you for reporting :)
We will need to test it further, but for the context, please know that `emu.str` is dependant on `asm.emu`, thus, will enable it when enabled by itself. So when `emu.str` changes from disabled to enabled, it will enable `asm.emu`, and when disabled, it will not disable `asm.emu`

**Comment by 0x913** [comment] 2020-02-12 15:04
Ah okay good to know :)

Also thank you for looking into it.

Have a nice day.

**Comment by karliss** [comment] 2020-02-12 16:43
Duplicate of #1694

**Closed** 2020-02-12 16:44 UTC
