### ISSUE TITLE
Ability to move nodes in the Graph view

### ISSUE THREAD

**Issue by Maijin** [radareorg/cutter#1326] opened 2019-03-18 08:38 UTC
**Is your feature request related to a problem? Please describe.**

Right now graph nodes can't be moved in the graph

**Describe the solution you'd like**

Add the ability to move the graphs in the Graph view

**Comment by ITAYC0HEN** [comment] 2020-07-17 15:47
Duplicate of the better-detailed issue https://github.com/radareorg/cutter/issues/2248 (which was opened later, but still)

**Closed by ITAYC0HEN** 2020-07-17 15:47 UTC
Labels: Enhancement
