### ISSUE TITLE
Link issues when  radare2 is built --with-sysmagic

### ISSUE THREAD

**Issue by edpil02** [radareorg/cutter#699] opened 2018-09-11 05:36 UTC
My distro built radare2 with --with-sysmagic , and i got link  errors when building cutter:
undefined reference to `r_magic_version'.
No issue when radare2 does not use the --with-sysmagic option.
Sorry for my english.

**Comment by xarkes** [comment] 2018-09-11 08:05
Ah indeed, must fix.

**Comment by xarkes** [comment] 2018-10-15 20:33
Oh really? Hmm interesting, I'm gonna ping/check in r2 side.

**Comment by exezin** [comment] 2018-10-15 20:36
Unless there's something else I am missing..

~~~
CMakeFiles/Cutter.dir/Cutter.cpp.o: In function `CutterCore::cmd(QString const&)':
Cutter.cpp:(.text+0xd8a): undefined reference to `r_core_task_sync_begin'
Cutter.cpp:(.text+0xdc0): undefined reference to `r_core_task_sync_end'
CMakeFiles/Cutter.dir/Cutter.cpp.o: In function `CutterCore::cmdj(QString const&)':
Cutter.cpp:(.text+0x104e): undefined reference to `r_core_task_sync_begin'
Cutter.cpp:(.text+0x1084): undefined reference to `r_core_task_sync_end'
CMakeFiles/Cutter.dir/Cutter.cpp.o: In function `CutterCore::loadScript(QString const&)':
Cutter.cpp:(.text+0x16814): undefined reference to `r_core_task_sync_begin'
Cutter.cpp:(.text+0x16865): undefined reference to `r_core_task_sync_end'
CMakeFiles/Cutter.dir/Cutter.cpp.o:(.data+0xe8): undefined reference to `r_magic_version'
CMakeFiles/Cutter.dir/utils/R2Task.cpp.o: In function `R2Task::startTask()':
R2Task.cpp:(.text+0x204): undefined reference to `r_core_task_enqueue'
CMakeFiles/Cutter.dir/utils/R2Task.cpp.o: In function `R2Task::breakTask()':
R2Task.cpp:(.text+0x29b): undefined reference to `r_core_task_break'
CMakeFiles/Cutter.dir/utils/ColorSchemeFileSaver.cpp.o: In function `ColorSchemeFileSaver::ColorSchemeFileSaver(QObject*)':
ColorSchemeFileSaver.cpp:(.text+0x3b5): undefined reference to `r_sys_prefix'
collect2: error: ld returned 1 exit status
CMakeFiles/Cutter.dir/build.make:2571: recipe for target 'Cutter' failed
make[2]: *** [Cutter] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/Cutter.dir/all' failed
make[1]: *** [CMakeFiles/Cutter.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
~~~

**Comment by xarkes** [comment] 2018-10-15 20:38
Oh, this looks like your r2 version is old. Make sure you don't have old r2 libraries in your system.

**Comment by exezin** [comment] 2018-10-15 23:58
It appears you are right, the latest version of r2 from the git repo appears to be having issues installing.  Seems to just segfault when even trying to print the version (r2 -v for example).

I've made sure to purge all previous library versions etc, might just be a bug in the latest version.

**Comment by exezin** [comment] 2018-10-16 00:15
Literally as I was debugging this issue a 3.0 release for r2 was added, compiling from that source seems to have resolved the issue   ¯\\\_(ツ)\_/¯

**Comment by xarkes** [comment] 2018-10-16 00:17
Ok I couldn't manage to reproduce, so thanks for the feedback.
What about you @edpil02, is this still an issue?

**Comment by edpil02** [comment] 2018-10-17 07:49
Test  from latest  git and fedora  radare2- 3.0.0-2.fc30  same issue : 

/bin/ld: CMakeFiles/Cutter.dir/Cutter.cpp.o:(.data+0xe8): undefined reference to `r_magic_version'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/Cutter.dir/build.make:1647: Cutter] Error 1
make[2]: Leaving directory '/home/rpmbuild/BUILD/cutter-1.7.2/src/build'
make[1]: *** [CMakeFiles/Makefile2:76: CMakeFiles/Cutter.dir/all] Error 2
make[1]: Leaving directory '/home/rpmbuild/BUILD/cutter-1.7.2/src/build'
make: *** [Makefile:87: all] Error 2
error: Bad exit status from /var/tmp/rpm-tmp.YY4oY0 (%build)

**Comment by radare** [comment] 2018-10-17 16:48
That's expected. and this bug is in Cutter, not in r2. As long as its built with sysmagic this symbol doesn't exist. so my proposal here is one of this:

* Use. r_userconf.h to determine if this symbol exists or not (like r2 do in radare2.c)

```
$ git grep r_magic_version
src/Cutter.cpp:        { "r_magic", &r_magic_version },
```

```
#if !USE_LIB_MAGIC
                { "r_magic", &r_magic_version },
#endif
```

* As alternative, just remove this line and it will not be a big loss and allow people to replace r2 instance without caring if its built with magic or not

**Comment by ITAYC0HEN** [comment] 2019-02-17 08:02
@xarkes any idea here? I think there are suggested solutions that can help us close this issue

**Comment by xarkes** [comment] 2019-02-17 10:14
Fixed in https://github.com/radareorg/cutter/pull/1195.

**Closed by xarkes** 2019-02-17 10:14 UTC
Labels: Build System
