### ISSUE TITLE
layout is not properly saved when you close and reopen Cutter.

### ISSUE THREAD

**Issue by Vane11ope** [radareorg/cutter#1220] opened 2019-02-27 09:07 UTC
Work Environment: Ubuntu 16.04 LTS

How to reproduce:

1. Go to "Reset layout" in the menu
2. Close Cutter
3. You will see the chaotic layout

I also attach the gif. I am fixing this anyway.
![gifrecord_2019-02-27_180042](https://user-images.githubusercontent.com/29271244/53478542-6c7d7480-3aba-11e9-8d21-018920d50445.gif)

**Comment by ITAYC0HEN** [comment] 2019-02-27 09:12
there are many more problems with layout, please try to figure all :)
for example, try to reset layout when a widget (say, Graph) is floating

**Comment by Vane11ope** [comment] 2019-02-27 09:18
@ITAYC0HEN cool but i might not be able to cover all by myself so plz list them up yourself too once you find any :)

**Comment by a1ext** [comment] 2019-02-27 09:24
There is a problem with layout on the first start on Windows:
![untitled](https://user-images.githubusercontent.com/14978853/53479671-32907c00-3a82-11e9-9e92-cf1897adad99.png)

(functions widget should be smaller, as after `Reset Layout`)

**Comment by Vane11ope** [comment] 2019-02-27 09:31
@a1ext 

windows.............................................................................................
I'll try my best and see and do whatever I can do, then I'm gonna have to ask you debugging for Windows later.......

**Comment by ITAYC0HEN** [comment] 2019-02-27 09:32
it's the same on Linux. The first execution of Cutter on all platforms looks like this. Instead of as expected (dashboard on focus, functions widget width 200px, etc)

**Comment by Vane11ope** [comment] 2019-02-27 09:34
nice, i mean not nice at all, but nice, because I will be able to debug it myself after I fix it.

**Comment by a1ext** [comment] 2019-02-27 09:40
> @a1ext
> 
> windows.............................................................................................
> I'll try my best and see and do whatever I can do, then I'm gonna have to ask you debugging for Windows later.......

haha) ok, to reproduce you have to remove Cutter config file

**Comment by Vane11ope** [comment] 2019-02-27 10:02
weird. reset settings and close then reopen fixed this completely and I can't reproduce the thing anymore. wtf.......

**Comment by xarkes** [comment] 2019-02-27 11:00
I think the best to solve this issue is to also fix this one:https://github.com/radareorg/cutter/issues/694

**Comment by Vane11ope** [comment] 2019-02-27 11:09
@xarkes cool im gonna check it out thanks :)

**Comment by a1ext** [comment] 2019-03-13 09:28
> hen reopen fixed this completely and I can't

try to pen extra disasm and graph windows

**Comment by ITAYC0HEN** [comment] 2019-03-18 06:45
fixed in #1308

**Closed by ITAYC0HEN** 2019-03-18 06:45 UTC
Labels: BUG, UI
