### ISSUE TITLE
Missing libzip-dev (zip static libraries) from cmake dependencies

### ISSUE THREAD

**Issue by snaiperskaya96** [radareorg/cutter#433] opened 2018-04-07 18:19 UTC
Now this isn't a real issue/bug as everything works as intended, however anyone using cmake expects to be aware of all the dependencies when running cmake (eg. you run `cmake ..` and it tells you are missing qt libraries and so on). You are just missing a check on libzip.

### Environment 
Sorry i'm not filling the environment section as it's irrelevant to this issue.

### Expected behavior
When compiling with cmake, i'd expect all the dependencies to be found when cmake is used
### Actual behavior
cmake runs successfully however while compiling with make the final linking fails if there is no libzip.a available 
### Steps to reproduce the behavior 
Any environment without libzip should fail

### Additional Logs, screenshots, source-code,  configuration dump, ...
```
[ 94%] Building CXX object CMakeFiles/Cutter.dir/utils/JsonModel.cpp.o
[ 95%] Building CXX object CMakeFiles/Cutter.dir/Cutter_autogen/mocs_compilation.cpp.o
[ 97%] Building CXX object CMakeFiles/Cutter.dir/Cutter_autogen/EWIEGA46WW/qrc_resources.cpp.o
[ 98%] Building CXX object CMakeFiles/Cutter.dir/Cutter_autogen/CHD5FKCWUD/qrc_style.cpp.o
[100%] Linking CXX executable Cutter
/usr/bin/ld: cannot find -lzip
```

The obvious fix is to add `find_package(Zip REQUIRED)` to the CMakeLists.
Have a nice day!

**Comment by xarkes** [comment] 2018-04-07 19:50
Thanks for reporting :)

**Comment by thestr4ng3r** [comment] 2018-04-12 10:09
Actually, libzip is not one of our direct requirements. In my case, the Cutter executable is not linked against it at all, so I assume it's either Qt or some other dependency doing something weird in your case.
Could you please give us some more info about your environment and also how exactly you installed radare2?

**Comment by thestr4ng3r** [comment] 2018-04-13 16:28
@snaiperskaya96 ping

**Comment by thestr4ng3r** [comment] 2018-04-13 16:29
@snaiperskaya96 ping

**Comment by snaiperskaya96** [comment] 2018-04-13 16:32
Sorry guys but I didn't have any chance to have a look at the setup I used.
I strongly believe it was a plain `cmake ..` on an almost out of the box
Ubuntu 18.04

**Comment by gamax92** [comment] 2018-04-13 19:44
For me, Cutter doesn't link against libzip either, the only thing I can find is (according to lddtree), a dependency to libminizip.so.1 by libQt5WebEngineCore.so.5

**Comment by thestr4ng3r** [comment] 2018-04-14 15:31
Can't reproduce it on a clean Ubuntu 18.04 Beta 2 installation with all possible combinations of enabling/disabling cutter and qtwebengine.

Sorry, but I can't do much more without specific info about the environment, r2 installation method and from where Qt is installed.

**Comment by xarkes** [comment] 2018-04-30 20:08
Closing because no one can reproduce.

**Closed by xarkes** 2018-04-30 20:08 UTC
