### ISSUE TITLE
define length of a string in cutter

### ISSUE THREAD

**Issue by andrewclarkii** [radareorg/cutter#1876] opened 2019-11-12 12:05 UTC
It would be great if you add this feature:

I have got this, when I marked code as a string:
.string "END OF MW_SHELL\xff\xff\xff\xff\xff\xff
And I want this:
.string "END OF MW_SHELL
and whole \xff define as dup X (ff)?

https://twitter.com/thestr4ng3r/status/1159042131962617856

**Comment by karliss** [comment] 2019-11-12 12:18
Duplicate of #1771

**Closed by karliss** 2019-11-12 12:18 UTC
Labels: Duplicate
