### ISSUE TITLE
Empty Disas on hello-world main function compiled with debug symbols

### ISSUE THREAD

**Issue by Rehan-MALAK** [radareorg/cutter#538] opened 2018-06-12 23:00 UTC
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Debian GNU/Linux unstable (sid)
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | x86/64
| Cutter and r2 version, See About Cutter (mandatory)  | Version 1.4 81aa85e46 / Using r2 2.6.0-142-g0ed78a567

linux  4.16.0-2-amd64 Debian 4.16.12-1
gcc version 7.3.0 (Debian 7.3.0-21)
GNU ld (GNU Binutils for Debian) 2.30
ldd (Debian GLIBC 2.27-3) 2.27

### Expected behavior

Double click on a function name would show its content.

### Actual behavior

The disas view is showing empty content on few functions including the main function.

### Steps to reproduce the behavior 

```c
#include <stdio.h>

int main (int argc,char *argv[])
{
    printf("Hello World!\n");
    return 0;
}
```
compiled **with debug symbols** <code>gcc -g hello.c -o hello</code>

then cutter can't go in sym.main, we have indeed a new **pdJ** problem (as in #482 for example) :

**Failed to parse JSON for command "pdJ 32 @ 1594": unterminated object**

### Additional Logs, screenshots, source-code,  configuration dump, ...

https://gist.github.com/Rehan-MALAK/ea753bd495841c79bfda32bb56c1f270#file-hello-world-with-debug-cutter-log-txt

**Comment by xarkes** [comment] 2018-06-13 07:29
Hi,
Can you provide the exact binary so it's easier for us to reproduce?
Thanks!

**Comment by xarkes** [comment] 2018-06-13 07:35
Nevermind I found the bug. Will fix later.

**Comment by xarkes** [comment] 2018-06-26 09:46
Cannot find the commit, but it's been fixed on radare2 master branch.

**Comment by Rehan-MALAK** [comment] 2018-07-02 14:22
No, it seems that it has not been resolved.

### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Debian GNU/Linux unstable (sid)
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | x86/64
| Cutter and r2 version, See About Cutter (mandatory)  | Version 1.4 520bee81d / Using 2.6.0-402-g896b987f9

linux  4.16.0-2-amd64 Debian 4.16.16-2
gcc version 7.3.0 (Debian 7.3.0-24)
GNU ld (GNU Binutils for Debian) 2.30.90.20180627
ldd (Debian GLIBC 2.27-3) 2.27

### Expected behavior

Double click on a function name would show its content.

### Actual behavior

The disas view is showing empty content on few functions including the main function.

### Steps to reproduce the behavior 

```c
#include <stdio.h>

int main (int argc,char *argv[])
{
    printf("Hello World!\n");
    return 0;
}
```
compiled **with debug symbols** <code>gcc -g hello.c -o hello</code>

then cutter can't go in sym.main, we have indeed a new **pdJ** problem (as in #482 for example) :

this time I get

**Failed to parse JSON for command "pdJ 13 @ 4442": unterminated object**

### Additional Logs, screenshots, source-code,  configuration dump, ...

https://gist.github.com/Rehan-MALAK/dfd07f3bafa84cea656aaf95c5aa0790

**Comment by Rehan-MALAK** [comment] 2018-07-02 21:52
[hello.zip](https://github.com/radareorg/cutter/files/2156914/hello.zip)

**Comment by Maijin** [comment] 2018-07-03 02:51
Can't reproduce, @xarkes ?

**Comment by xarkes** [comment] 2018-07-03 08:03
![2018-07-03-095416_1313x452_scrot](https://user-images.githubusercontent.com/10772605/42206339-1b10457a-7ea7-11e8-885a-a87be3517113.png)
Can't reproduce either. This is strange because your radare2 version looks up to date.
I don't understand what's happening here to be honest.

What I can suggest is to try with the 1.5 AppImage file. (Available [here](https://github.com/radareorg/cutter/releases/download/v1.5/Cutter-v1.5-x86_64.AppImage))

Then, maybe you should try purging radare2 (uninstalling and removing everything, make sure the libraries are uninstalled), then purging Cutter as well, deleting any configuration file (~/.config/Cutter), and then reinstalling properly everything...

**Comment by Rehan-MALAK** [comment] 2018-07-03 16:15
Hi ! thanks for your replies... 
Unfortunately, I can reproduce the bug, even with the 1.5 AppImage file.
Your output looks like my hello-world **without** the debug symbols...

![hello-world-nodbg](https://user-images.githubusercontent.com/39339802/42230454-576e9c46-7ee9-11e8-836b-524604b041d3.png)

instead of 

![hello-world-dbg](https://user-images.githubusercontent.com/39339802/42230482-6924eb70-7ee9-11e8-9249-828ad524aed0.png)

For example, if I restrain to the problematic line in radare2  ''pdJ 1 @ 0x00001169''

with the no-debug symbol hello-world

![hello-world-nodbg-json-online-parser](https://user-images.githubusercontent.com/39339802/42231428-ccd89520-7eeb-11e8-930c-27e7898fc31c.png)

but with the debug symbols hello-world

![hello-world-dbg-json-online-parser](https://user-images.githubusercontent.com/39339802/42231465-e3020840-7eeb-11e8-92f4-5b07c1ad9533.png)

and , I need to escape the two double quote marks to get a correct json parsing...

![hello-world-dbg-json-online-parser-escape-quote-marks](https://user-images.githubusercontent.com/39339802/42231577-2d703352-7eec-11e8-9124-bbc5f24700b9.png)

**Comment by xarkes** [comment] 2018-07-04 09:06
Alright, sorry that's my bad, I don't know why I couldn't reproduce the first time...
Will fix.

**Closed** 2018-07-04 10:07 UTC
Labels: bug, radare2
