### ISSUE TITLE
Cut off function in graph view and decompiler view

### ISSUE THREAD

**Issue by c0rund** [radareorg/cutter#1787] opened 2019-09-24 07:53 UTC
**Environment information**
* Operating System: Manjaro linux x64 (kernel 5.1.21)
* Cutter version: Cutter 1.9.0 r2-3.8.0
* File format: elf64. Downloaded here: http://csapp.cs.cmu.edu/3e/bomb.tar
**Describe the bug**
Function : main. In graph view and in decompiler view last instruction in block with code last addres - 0x00400e72 ( call sym.phase_3 ) But it not end of function. Ret in 0x00400ed6.  In Cutter 1.8.3  all work.

**To Reproduce**
Auto Analysis :Enabled
Level: Auto-analysis (aaa)

**Screenshots**
![07](https://user-images.githubusercontent.com/55733259/65492124-0e323c00-deb9-11e9-97a2-7088da8dc1ef.png)
<!-- If applicable, add screenshots to help explain your problem

**Comment by xarkes** [comment] 2019-09-24 08:11
It looks like an analysis issue inside radare2.

**Comment by pelijah** [comment] 2019-10-12 20:14
Can't reproduce. 
![изображение](https://user-images.githubusercontent.com/16493991/66707244-080bde80-ed46-11e9-9b00-938ee5e4510b.png)

**Comment by pelijah** [comment] 2019-10-12 20:19
But it is one of the latest builds from AppVeyor.

**Comment by ITAYC0HEN** [comment] 2019-10-31 10:47
@c0rund can you make sure it still happens on latest version of Cutter from git and of the decompiler?

Also, can you please try it from radare2 master version? (newest release would be okay as well). 
We want to make sure this is solved or not, and if no - we would like to transfer this issue to the radare2 repository

**Comment by c0rund** [comment] 2019-11-01 22:34
In last version from git:
Version 1.9.0 
Using r2-3.9.0-137-gf6036ffba 
Based on Qt 5.13.1 (GCC 9.2.0, 64 bit))

All work correct and problem don't reproduce

**Comment by ITAYC0HEN** [comment] 2019-11-01 22:35
great! so I'll close this issue. thank you for reporting, you helped a lot.
please don't hesitate to open more issues when you encounter problems with Cutter. :)

**Closed by ITAYC0HEN** 2019-11-01 22:35 UTC
Labels: BUG, radare2
