### ISSUE TITLE
Add `emu.str` configuration option to preferences window

### ISSUE THREAD

**Issue by ITAYC0HEN** [radareorg/cutter#1275] opened 2019-03-11 06:47 UTC
**Describe the solution you'd like**

Add `emu.str` configuration option to preferences window. This should be DISABLED by default since `emu.str` is too verbose.

**Comment by Maijin** [comment] 2019-03-11 06:50
Duplicate of #1276

**Closed by Maijin** 2019-03-11 06:50 UTC
Labels: Enhancement, good first issue

**Comment by radare** [comment] 2019-03-11 08:31
Maybe too verbose for x86. For arm is mandatory. And without that var u dont resolve the fcn call args
