### ISSUE TITLE
Cutter unable to open an apk

### ISSUE THREAD

**Issue by ytrewqytrewqytrewqytrewq1** [radareorg/cutter#802] opened 2018-10-11 09:47 UTC
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             |  Ubuntu 17 64bit
| File format of the file you reverse (mandatory)      | apk
| Architecture/bits of the file (mandatory)            | N/A
| Cutter and r2 version, See About Cutter (mandatory)  | Version 1.7.2 / Using r2 2.9.0-310-gcb62c376b
| Show version information **full output** (See About Cutter) in a pastebin document (mandatory) | https://pastebin.com/vJXyxM2G

### Expected behavior
Cutter should open the apk and decompile the dex files
### Actual behavior
log:
`r_core_file_open failed
`
pop up 
> Cannot open file!
> Could not open the file! Make sure the file exists and that you have the correct permissions.

### Steps to reproduce the behavior 
- start Cutter
- the IO select menu choose zip
- select an apk
- click on open
- in the next window ( Load Options) click ok
- error
[c.zip](https://github.com/radareorg/cutter/files/2468359/c.zip)

### Additional Logs, screenshots, source-code,  configuration dump, ...

Drag and drop zip archives containing the Additional info here, don't use external services or link.

**Comment by ITAYC0HEN** [comment] 2018-10-11 22:13
Reproduced on master:
![image](https://user-images.githubusercontent.com/20182642/46836429-0cf82400-cdba-11e8-939a-d38ac9138034.png)

as far as I remember, `zip://` doesn't open the file but only list the files inside. I'm not sure though...
In such case, `zip://` should be removed from Cutter.
On the other hand, there's an `apk://` IO option which for some reason doesn't exist in our list. We should fix this.

Tried with r2 and `zip://test.apk` list the files inside and output "r_core_file_open failed" while using `apk://test.apk` opened the apk in the `classes.dex` file.

@xarkes maybe you'll have more insights

**Comment by ITAYC0HEN** [comment] 2018-10-12 07:16
Good idea :)

> as far as I remember, zip:// doesn't open the file but only list the files inside

@XVilka, do you remember if the quoted above is true?

**Comment by ytrewqytrewqytrewqytrewq1** [comment] 2018-10-12 07:17
@ITAYC0HEN if you position your mouse over zip in the IO selection input field a description appears which lists apk between the supported files types for zip

**Comment by ITAYC0HEN** [comment] 2018-10-23 06:04
I'm closing this issue since the problem is in the differences between the console UI and the GUI. 
I opened a feature request for a dialog showing the list of files: #870

**Closed by ITAYC0HEN** 2018-10-23 06:04 UTC
