### ISSUE TITLE
Registers view does not show full registers

### ISSUE THREAD

**Issue by oliv3r** [radareorg/cutter#1858] opened 2019-10-23 08:08 UTC
**Environment information**
* Operating System: Linux
* Cutter version: Cutter-v1.9.0-x64.Linux.AppImage
* File format: arm32 little

**Describe the bug**
When opening the registers view, the values do not fit into the edit box. Worse, when resizing the pane, the edit boxes stay the same size, while the pane grows.

**Screenshots**
![image](https://user-images.githubusercontent.com/1245341/67371617-f2d05480-f57c-11e9-81fe-d26b690c9223.png)

**Comment by karliss** [comment] 2019-10-23 20:06
@oliv3r Are you running Cutter on high DPI monitor or otherwise increased scaling factor? Size of some other elements also doesn't look right.

**Comment by oliv3r** [comment] 2019-10-24 18:40
Yes and no;
I took this screenshot while I was indeed on a 4k HiDPI 200% scale screen. When I connect my external monitors however, I run at 100% scale, but change the resolution of my laptop screen. Cutter on the normal monitor then looks quite big and has the same problem. I am not restarting the application in between however.

**Comment by ITAYC0HEN** [comment] 2019-12-14 16:25
I made some changes to the view, can you check now? @oliv3r

**Comment by ITAYC0HEN** [comment] 2020-01-02 08:33
ping @oliv3r :)

**Comment by ITAYC0HEN** [comment] 2020-01-21 06:28
I can't reproduce after the modifications. I'll close it for now. Feel free to re-open it if you are experiencing it again.
 :)

**Closed by ITAYC0HEN** 2020-01-21 06:28 UTC
Labels: BUG, Debug, UI
