### ISSUE TITLE
Useless / not working help button on update downloader popup

### ISSUE THREAD

**Issue by 0xThxmxs** [radareorg/cutter#2424] opened 2020-09-05 15:40 UTC
**Environment information**
* Operating System: Windows 10
* Cutter version: 1.11.1 (when update to 1.12.0)
* File format: ELF64
 * Arch: x86_64
 * Type: Executable file

**Bug description**
Nothing append when clicking the help / information button of the update downloader popup, but the cursor change to forbidden icon. Another click will restore normal cursor icon.

**To reproduce**
1. Make Cutter have to update
2. Open it and accept the update on update checker popup
3. Click on the "?" button of the downloader popup

**Expected behavior**
Get changelog of the next version ?

**Screenshots**
![bug](https://user-images.githubusercontent.com/62804686/92308413-a5df4c00-ef9d-11ea-87fb-affcc28eee3e.gif)

**Additional context**
I was updating Cutter 1.11.1 to Cutter 1.12.0.

**Comment by ITAYC0HEN** [comment] 2020-09-05 15:50
Thank you for reporting this issue :) 
This issue is Related / Duplicate of https://github.com/radareorg/cutter/issues/2342

**Closed** 2020-09-05 15:53 UTC
Labels: Duplicate
