### ISSUE TITLE
Double Cutter title in macOS

### ISSUE THREAD

**Issue by radare** [radareorg/cutter#1040] opened 2018-12-27 00:09 UTC
<img width="873" alt="screenshot 2018-12-27 at 01 08 55" src="https://user-images.githubusercontent.com/917142/50460199-1c781980-0974-11e9-87f3-3260f9e93f4e.png">

**Comment by thestr4ng3r** [comment] 2018-12-27 12:42
duplicate of https://github.com/radareorg/cutter/issues/290

**Closed by thestr4ng3r** 2018-12-27 12:42 UTC
Labels: duplicate, enhancement, good first issue, macOS
